ceph/cephmetrics

ansible/ansible.cfg, ansible/playbook.yml, ansible/roles/ceph-collectd/defaults/main.yml, ansible/roles/ceph-collectd/tasks/install_collectd_plugins.yml, ansible/roles/ceph-collectd/tasks/install_packages.yml, ansible/roles/ceph-collectd/tasks/main.yml, ansible/roles/ceph-collectd/tasks/start_collectd.yml
=> Add initial ansible role for collectors

ansible/roles/ceph-grafana/tasks/configure_grafana.yml
=> Set domain and root_url in grafana.ini

ansible/roles/ceph-grafana/defaults/main.yml, ansible/roles/ceph-grafana/tasks/configure_grafana.yml, ansible/roles/ceph-grafana/tasks/configure_graphite.yml
=> Allow configuring Graphite port

ansible/common/files/cephmetrics.repo, ansible/roles/ceph-collectd/defaults/main.yml, ansible/roles/ceph-collectd/files/cephmetrics.repo, ansible/roles/ceph-collectd/tasks/install_collectd_plugins.yml, ansible/roles/ceph-collectd/tasks/install_packages.yml, ansible/roles/ceph-grafana/defaults/main.yml, ansible/roles/ceph-grafana/files/cephmetrics.repo, ansible/roles/ceph-grafana/tasks/configure_carbon.yml, ansible/roles/ceph-grafana/tasks/configure_firewall.yml, ansible/roles/ceph-grafana/tasks/configure_grafana.yml, ansible/roles/ceph-grafana/tasks/configure_graphite.yml, ansible/roles/ceph-grafana/tasks/install_packages.yml, dashUpdater.py
Main features:
* By default pulls packages from a ceph.com repo instead of EPEL
* Fixes issues with older ansible versions
* Fixes a few minor dependency issues
=> More ansible updates

ansible/roles/ceph-grafana/handlers/main.yml, ansible/roles/ceph-grafana/tasks/configure_carbon.yml, ansible/roles/ceph-grafana/templates/storage-schemas.conf
=> Resize whisper databases when necessary

ansible/roles/ceph-grafana/tasks/configure_carbon.yml
=> Ensure /var/lib/carbon has the right ownership

ansible/roles/ceph-grafana/files/grafana.ini, ansible/roles/ceph-grafana/tasks/configure_grafana.yml, etc/grafana/grafana.ini
=> Ship grafana.ini from this repo

ansible/roles/ceph-grafana/tasks/configure_grafana.yml, ansible/roles/ceph-grafana/tasks/grafana_plugins.yml, cephmetrics.spec.in, collectors/mon.py, collectors/osd.py, collectors/rgw.py, selinux/cephmetrics.te
This contains a fix for ansible where we start grafana way too early (before we modify its config file), adds rpm support for piechart plugin and fixes collectors constructors so that they support log_level keyword argument.
=> Couple of cephmetric fixes

collectors/mon.py, tox.ini
=> Add tox.ini with flake8 job

ansible/roles/ceph-grafana/defaults/main.yml
This will be appropriate for most users.
=> ansible: Default to using firewalld's public zone

ansible/README.md
=> ansible: Document variables

ansible/roles/ceph-collectd/files/cephmetrics.te, ansible/roles/ceph-collectd/tasks/install_packages.yml, ansible/roles/ceph-collectd/tasks/main.yml, ansible/roles/ceph-collectd/tasks/selinux.yml, ansible/roles/ceph-collectd/tasks/selinux_module.yml, selinux/cephmetrics.te
=> ansible: Build and install SELinux module

tox.ini
=> Add ansible-syntax job

ansible/roles/ceph-grafana/tasks/configure_carbon.yml
Related to https://github.com/ceph/cephmetrics/issues/45
=> Set WHISPER_AUTOFLUSH to True

ansible/purge.yml
=> ansible: Fix a typo in purge.yml

cephmetrics.spec.in
=> rpm: Support light theme better

README.md
Signed-off-by: Warren Usui <wusui@magna002.ceph.redhat.com>
=> Non-developer installation instructions

ansible/README.md, ansible/roles/ceph-grafana/defaults/main.yml, ansible/roles/ceph-grafana/tasks/configure_carbon.yml
Fixes https://github.com/ceph/cephmetrics/issues/61
=> Make whisper retention settings configurable

collectors/common.py, collectors/osd.py
=> Dmcrypt support

collectors/iscsi.py
the goal of the parent module cephmetrics is to be generic across the
different ceph roles. By deferring the import of rtslib to the instantiation
of the first (and only!) ISCSIGateway object cephmetrics can import this
iscsi module without a problem regardless of the runtime environment.
=> iscsi.py: fix to defer the import of rtslib_fb

cephmetrics.spec.in
=> rpm: Fix spec file source versioning

ansible/ansible.cfg
See http://docs.ansible.com/ansible/latest/become.html#becoming-an-unprivileged-user
=> Use SSH pipelining

cephmetrics.py, collectors/base.py, collectors/common.py, collectors/iscsi.py, collectors/mon.py, collectors/rgw.py
this PR basically soft fails socket read fails allowing the collectors to keep checking for admin sockets, so ceph service restarts don't need collectd restarts
=> Support svc restarts

ansible/README.md, ansible/roles/ceph-grafana/defaults/main.yml, ansible/roles/ceph-grafana/tasks/configure_grafana.yml, collectors/mon.py, dashUpdater.py, dashboards/current/alert-status.json, dashboards/current/ceph-cluster.json, dashboards/current/ceph-pools.json
https://github.com/ceph/cephmetrics/issues/104
=> Collect more pool stats, and display capacity in dashboard

ansible/roles/ceph-grafana/templates/dashboard.yml
=> Don't forget to deploy the new health dashboard

etc/collectd.d/cephmetrics.conf
So that users can generate more useful bug reports.
=> Tell collectd to log any Python tracebacks

dashboards/current/ceph-at-a-glance.json, dashboards/current/ceph-backend-storage.json, dashboards/current/iscsi-overview.json, dashboards/current/network-usage-by-node.json
Updating 4 dashboards following feedback from testing in Sepia, further iscsi work and feedback from the large scale deployment in a partner lab (network stats)
=> dashboard changes

dashboards/current/alert-status.json
last() appears to invite flapping.
=> alert-status: Use max() for health alert condition

ansible/README.md, ansible/common/templates/cephmetrics-custom.repo, ansible/roles/ceph-collectd/tasks/setup_repos.yml, ansible/roles/ceph-collectd/templates/cephmetrics-custom.repo, ansible/roles/ceph-grafana/tasks/setup_repos.yml, ansible/roles/ceph-grafana/templates/cephmetrics-custom.repo
This is a follow-up to #124 - but I need to test it before we merge.
=> Add support for custom repos

ansible/roles/ceph-grafana/tasks/configure_firewall.yml, ansible/roles/ceph-grafana/tasks/main.yml, ansible/roles/ceph-grafana/tasks/sanity.yml
https://github.com/ceph/cephmetrics/issues/123
=> Check that all hosts are referred to by FQDN

ansible/playbook.yml
Boris - let me know if this message is useful please!
=> Add a note about waiting to collect data

dashboards/current/ceph-at-a-glance.json, dashboards/current/ceph-osd-information.json, dashboards/current/ceph-pools.json, dashboards/current/osd-node-detail.json
Dashboard updates to address the anomalies reported in BZ1496196/1499734/1498504
=> Ui bz fixes

ansible/roles/ceph-collectd/tests/test_collectd.py, ansible/roles/ceph-grafana/tests/test_grafana.py, tox.ini
These aren't exhaustive, but they're a start.
Edit: They'll also be useful once we get some teuthology support going - it will pretty much just have to run the playbook, then tox, to take advantage of anything we add here.
=> Add some integration tests using testinfra

ansible/roles/ceph-grafana/tasks/add_notification_channel.yml, ansible/roles/ceph-grafana/tasks/configure_grafana.yml
=> ceph-grafana: Add notification channel

ansible/roles/ceph-docker/tests/test_docker.py
=> ceph-docker: Update tests for 'containerized' flag

ansible/roles/ceph-collectd/tasks/selinux.yml
The file doesn't exist with bluestore.
=> ceph-collectd: Only set SEL context on filestore

ansible/README.md, ansible/roles/ceph-collectd/tasks/install_packages.yml, ansible/roles/ceph-grafana/tasks/setup_repos.yml, ansible/roles/cephmetrics-common/defaults/main.yml, ansible/roles/cephmetrics-common/tasks/setup_repos.yml
This needs just a bit of testing
=> Drop use_epel flag

ansible/roles/ceph-grafana/tasks/push_dashboards.yml, ansible/roles/ceph-node-exporter/tasks/configure_firewall.yml, dashboards/mgr-prometheus/network-usage-by-node.json
=> Fix mon_server queries in network-usage-by-node and set home db

dashboards/mgr-prometheus/ceph-osd-information.json
Too many to list here; almost every panel was
broken in some regard.
=> ceph-osd-information: Fix numerous bugs

dashboards/mgr-prometheus/alert-status.json, dashboards/mgr-prometheus/ceph-at-a-glance.json, dashboards/mgr-prometheus/ceph-backend-storage.json, dashboards/mgr-prometheus/ceph-cluster.json, dashboards/mgr-prometheus/ceph-health.json, dashboards/mgr-prometheus/ceph-osd-information.json, dashboards/mgr-prometheus/ceph-pools.json, dashboards/mgr-prometheus/ceph-rgw-workload.json, dashboards/mgr-prometheus/cephmetrics-host.json, dashboards/mgr-prometheus/disk-busy-by-server.json, dashboards/mgr-prometheus/iops-by-server.json, dashboards/mgr-prometheus/iscsi-client-details.json, dashboards/mgr-prometheus/iscsi-overview.json, dashboards/mgr-prometheus/latency-by-server.json, dashboards/mgr-prometheus/mds-performance.json, dashboards/mgr-prometheus/network-usage-by-node.json, dashboards/mgr-prometheus/osd-node-detail.json
=> Make dashboards uneditable by default

ansible/roles/ceph-node-exporter/defaults/main.yml, dashboards/mgr-prometheus/osd-node-detail.json
This should fixed an issue that I noticed while testing and a QE issue in rhbz#1539663.
=> Downstream fixes

ansible/roles/ceph-mgr/tasks/configure_firewall.yml, ansible/roles/ceph-mgr/tasks/main.yml, ansible/roles/ceph-prometheus/tasks/configure_firewall.yml, ansible/roles/ceph-prometheus/tasks/main.yml
https://github.com/ceph/cephmetrics/issues/213
https://github.com/ceph/cephmetrics/issues/214
=> Open ports 9283 and 9090

dashboards/mgr-prometheus/alert-status.json, dashboards/mgr-prometheus/ceph-backend-storage.json, dashboards/mgr-prometheus/iscsi-client-details.json, dashboards/mgr-prometheus/iscsi-overview.json, dashboards/mgr-prometheus/network-usage-by-node.json, dashboards/mgr-prometheus/osd-node-detail.json
https://github.com/ceph/cephmetrics/issues/205
=> dashboards: Don't filter out 10GbE iface names

ansible/roles/ceph-node-exporter/tasks/configure_firewall.yml
Fixed bug : required port added in the file
=> firewalld: added port

patches/0001-ansible-Disable-devel_mode.patch
=> patches: Fix patch to apply cleanly

dashboards/mgr-prometheus/ceph-backend-storage.json
=> dashboards: Fix slow/inaccurate OSD down counter
