ceph/cephmetrics

- ansible/roles/ceph-grafana/defaults/main.yml
- ansible/roles/ceph-grafana/tasks/configure_grafana.yml
This behavior can be disabled by setting 'replace_dashboards' to False
> ansible: Replace dashboards by default when updating

- ansible/ansible.cfg
This speeds up deployment. Ansible will use this value or the number of
hosts - whichever is smaller.
> ansible: Use up to 50 forks

- selinux/cephmetrics.te
This was required to access whoami files inside /var/lib/ceph/osd/
directory.
> selinux: Additional policy changes

- cephmetrics.spec.in
This changes the default value for devel_mode in rpm packages during the build time.
> rpm: Make devel_mode: false default in the ansible rpms

- ansible/purge.yml
This should be a good basis for purge playbook, it should support devel
as well as production modes.
I have tested this on my test cluster and it seemed to work fine.
> ansible: Implement purge playbook

- README.md
It's needed for pyserial, python-twisted-core and python-zope-interface,
which are dependencies of python-carbon
Fixes issue #56
> Mention enabling rhel-7-server-optional-rpms

- cephmetrics.spec.in
We do not really need this dependency and it can help separate the dependencies for the main server and the collectors running on the monitors.
> rpm: Drop collectors dependency for main package

- ansible/README.md
- ansible/roles/ceph-grafana/defaults/main.yml
Related to https://github.com/ceph/cephmetrics/issues/82
This provides `devel_mode` functionality for CentOS 7.
> Support CentOS 7 in devel_mode

- ansible/roles/ceph-grafana/templates/dashboard.yml
- cephmetrics.py
- collectors/iscsi.py
- dashboard.yml
- dashboards/current/iscsi-overview.json
This PR adds an iscsi overview dashboard, and an associated collector to gather performance and configuration metrics from LIO. At this stage the dashboard is not linked to from the at-a-glance dashboard.
> Add iSCSI gateway support

- ansible/roles/ceph-grafana/defaults/main.yml
- ansible/roles/ceph-grafana/handlers/main.yml
- ansible/roles/ceph-grafana/tasks/configure_graphite_web.yml
- ansible/roles/ceph-grafana/tasks/start_services.yml
Because of https://github.com/brutasse/graphite-api/issues/222
Signed-off-by: David Galloway <dgallowa@redhat.com>
> ansible: Use graphite-web instead of graphite-api on Ubuntu

- ansible/roles/ceph-grafana/tasks/configure_graphite_web.yml
- ansible/roles/cephmetrics-common/defaults/main.yml
Oddly, graphite defaults to using a hardcoded timezone rather than the
system's. This throws off queries, so let's configure it.
> Set timezone in Graphite's config

- collectors/mon.py
_get_pool_stats() already replaces '.' with '_'; let's copy that
behavior
> Mon._get_df_stats(): Sanitize pool names

- collectors/rgw.py
glob pattern used didn't work for some rgw releases. this change covers a broader range of rgw socket names
> rgw: update glob pattern used to detect rgw sockets

- selinux/cephmetrics.te
Policy update needed to account for the way the ceph environment
is detected when collectd starts up.
> selinux policy update

- ansible/roles/ceph-collectd/tasks/configure_collectd.yml
- ansible/roles/ceph-collectd/tasks/install_collectd_plugins.yml
- ansible/roles/ceph-collectd/tasks/main.yml
- ansible/roles/ceph-collectd/tasks/set_collectd_vars.yml
We regressed by moving the definition of a couple of these vars. Set
them in a separate task file to avoid this in the future.
> Fix undefined collectd vars

- ansible/roles/ceph-collectd/files/cephmetrics-prod.repo
- ansible/roles/ceph-grafana/files/cephmetrics-prod.repo
This fixes the build failure after the patch that removed the original
repo file.
> ansible: Remove references to old prod repo

- ansible/roles/ceph-grafana/tasks/setup_repos.yml
- ansible/roles/cephmetrics-common/defaults/main.yml
We are shipping as a regular product and as such, we cannot enable
additional repos via rhsm. The customers might even not have these repos
installed (especially the storage console repo might not be available to
them).
If we need any of the packages from these repos, we need to cross-ship
them in our product (as we already do downstream).
> ansible: Do not enable rhsm repos

- dashboards/current/ceph-at-a-glance.json
- dashboards/current/ceph-osd-information.json
ceph-at-a-glance: Capacity util panel now links directly to the capacity
chart in the ceph-cluster dashboard BZ 1496198
ceph-osd-information: query timespan changed from the default 1hr to 1m
aligning to the OSDs panel query on the 'at-a-glance' dashboard
BZ 1498504
> dashboard updates to address minor usability issues

- ansible/roles/ceph-grafana/tasks/grafana_plugins.yml
The plugin recently added a system for configurable colors, breaking our
earlier hack. Add a new one.
See: https://github.com/Vonage/Grafana_Status_panel/commit/8633ba23bb2f336342ba3f7002a07be597b6e816
> Tweak Vonage panel color in newer versions

- cephmetrics.spec.in
It's needed by dashUpdater.py. BZ1497198
> Ensure PyYAML is installed on the Grafana node

- collectors/osd.py
We currently do not check that we were able to successfully fetch the
osd_stas for a given osd_id which can result in collectors being down
for a while. We should check that we were able to fetch them before we
actually try to update them.
> collectors: No update on fetch osd_stats failure

- cephmetrics.spec.in
This is required by ansible in order to enable the `collectd_tcp_network_connect` boolean
> Require libsemanage-python on collector nodes

- ansible/roles/ceph-grafana/tasks/configure_graphite_web.yml
- ansible/roles/cephmetrics-common/defaults/main.yml
I'm unsure if this is all we need to support CentOS. It does, however, get our teuthology jobs using CentOS to pass at least part of the time, instead of never:
http://pulpito.ceph.com/zack-2017-10-26_22:32:24-cephmetrics-master-distro-basic-vps/
> ansible: Fixes for CentOS deployments

- cephmetrics.spec.in
btw: There is no need to add this to the ansible scripts for devel mode, it is already there.
> rpm: Require python-requests

- ansible/purge.yml
This request is for fixing a typo found in the purge.yml file during some testing of a Ceph Metrics cluster.
The file lists /var/lig/graphite-web rather than /var/lib/graphite-web
> Fix a typo in the purge.yml Ansible playbook file

- ansible/README.md
- ansible/group_vars/all.yml.sample
- ansible/playbook.yml
- ansible/purge.yml
- ansible/roles/ceph-collectd/tasks/main.yml
- ansible/roles/ceph-docker/tasks/main.yml
- ansible/roles/ceph-grafana/defaults/main.yml
- ansible/roles/ceph-grafana/tasks/configure_grafana.yml
- ansible/roles/ceph-grafana/tasks/main.yml
- ansible/roles/ceph-grafana/tasks/push_dashboards.yml
- ansible/roles/ceph-grafana/tasks/setup_container.yml
- ansible/roles/ceph-grafana/templates/dashboard.yml
- ansible/roles/ceph-graphite/tasks/main.yml
- ansible/roles/ceph-prometheus/defaults/main.yml
- ansible/roles/ceph-prometheus/tasks/main.yml
- ansible/roles/ceph-prometheus/tasks/sanity.yml
- ansible/roles/ceph-prometheus/tasks/setup_container.yml
- ansible/roles/cephmetrics-common/defaults/main.yml
- ansible/roles/cephmetrics-common/tasks/main.yml
This will also help us fix of accessing these variables in ceph-docker
role where they were not defined previously.
> Add a couple of ansible fixes

- ansible/roles/ceph-grafana/tasks/add_notification_channel.yml
We missed this when merging #165 & #170
> ceph-grafana: Use 'admin_user', not 'user'

- ansible/playbook.yml
- ansible/roles/ceph-node-exporter/tasks/configure_firewall.yml
- ansible/roles/ceph-node-exporter/tasks/main.yml
- ansible/roles/ceph-prometheus/templates/prometheus.yml
- dashboards/mgr-prometheus/cephmetrics-host.json
A current issue with this is that the "filesystem usage" panel depends on `/var/lib/cephmetrics/data` being on a separate mountpoint.
> Monitor the dashboard host

- tox.ini
1.14.0 has been released with the fix we needed.
> Unpin testinfra

- cephmetrics.spec.in
This removes and obsoletes all the packages other than cephmetrics, moves the ansible scripts into the main cephmetrics package while setting provides for cephmetrics-ansible package to the cephmetrics package -- i.e. you can still install the ansible scripts with `yum install cephmetrics-ansible` but it will install the `cephmetrics` package.
The collectors, grafana-plugins as well as the old cephmetrics packages no longer make sense in context of latest cephmetrics.
> rpm: Update spec file for recent changes

- dashboards/mgr-prometheus/ceph-cluster.json
We were using 'id', not 'ceph_daemon' and as a result that column wasn't
showing up.
> ceph-cluster: Fix column styles for version tables

- dashboards/mgr-prometheus/iscsi-overview.json
All node_exporter scrapes are now done under the
same job (called node) so the dashboard now uses
an updated template query to identify the correct
host to pull out the OS metrics by iscsi gateway
> Updated to use OS metrics from default scrape job

- dashboards/mgr-prometheus/ceph-rgw-workload.json
Added multiple charts showing GET/PUT latencies
at overview and RGW detail levels. In addition
the failed HTTP request panel has been changed
from a singlestat to a graph to visualize the
failure rates across all RGW instances.
> Added RGW GET/PUT Latencies

- dashboards/mgr-prometheus/ceph-osd-information.json
Bluestore tables and charts updated, including;
- switched units from ms to secs which shows us too
- changed metric from commit to KV latency
- updated thresholds in bluestore tables
- switched from rate to irate for bluestore metrics
- updated bluestore text box description
> Multiple fixes to OSD information dashboard

- dashboards/cephmetrics-graphite/ceph-pools.json
- dashboards/mgr-prometheus/ceph-pools.json
Throughput units were using binary representation,
whereas the expected unit is decimal (i.e.
MB/s not MiB/s)
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1496186
> Fix units used for throughput

- patches/0001-ansible-Disable-devel_mode.patch
We need to strip this away from the downstream patch.
> rpm: use_epel is no longer defined

- ansible/group_vars/all.yml.sample
- ansible/roles/ceph-mgr/tasks/main.yml
- ansible/roles/cephmetrics-common/defaults/main.yml
We only call the ceph command once and the command fails for non-standard cluster names. This should fix it, see the downstream bz for the details:
https://bugzilla.redhat.com/show_bug.cgi?id=1608863
> ansible: Support non-default cluster name

- ansible/playbook.yml
We do not need to run the ceph-mgr role multiple times. The command that
enables the module only need to be run on one of the machines, choosing
first as it is the easiest.
> Only run ceph-mgr role on a single node

- ansible/roles/ceph-node-exporter/defaults/main.yml
> ceph-node-exporter: Fix defaults for service_name

- dashboards/mgr-prometheus/alert-status.json
This also re-arranges the alerting panels to (5, 5, 3) from (6, 6, 1) to avoid having a single panel in the last row.
> dashboards: Add error panel+alerting

- ansible/roles/ceph-prometheus/defaults/main.yml
- ansible/roles/ceph-prometheus/tasks/setup_container.yml
This only supports containerized deployments.
> ceph-prometheus: Optionally add /etc/hosts entries

- dashboards/mgr-prometheus/ceph-at-a-glance.json
- dashboards/mgr-prometheus/ceph-health.json
Two dashboards were translating the values from
ceph_health_status incorrectly, resulting in
the wrong health state being shown.
Closes: https://github.com/ceph/cephmetrics/issues/202
> Fix health state colors

- dashboards/mgr-prometheus/ceph-cluster.json
We still use the old 'id' label for getting the number of OSDs in the
ceph cluster dashboard. However, the label was superseded by the
'ceph_daemon' label in one of the updates to the prometheus exporter in
ceph-mgr. This patch changes the query to what we use in other
dashboards -- i.e. 'ceph_daemon' instead of 'id'.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1627725
> dashboards: Fix cluster OSDs panel

- dashboards/mgr-prometheus/osd-node-detail.json
Host breakdown was hitting duplicate labels, and
the disk graphs needed a filter to only show the
disk stats for disks that relate to the host's
OSDs.
> Fix Host breakdown and disk graphs

- ansible/roles/ceph-grafana/defaults/main.yml
- ansible/roles/ceph-grafana/tasks/setup_container.yml
- ansible/roles/ceph-prometheus/defaults/main.yml
- ansible/roles/ceph-prometheus/tasks/setup_container.yml
This patch add a new prometheus and grafana variable to allow install when the images already pulled on docker.
> Prevent pull images for prometheus and grafana

- ansible/group_vars/all.yml.sample
- ansible/roles/ceph-grafana/defaults/main.yml
- ansible/roles/ceph-grafana/tasks/configure_grafana.yml
We are using cepmetrics for alerting via mail. Each time something changes at the deployment our SMTP settings get overwritten. With these changes, basic SMTP settings can be done via variables.  
We also use status monitors, displaying some grafana playlists. Those monitors should not be that bright, that's why we prefer to use the dark theme, which can now also be configured via variables.  
Finlay, we use anonymous login for those monitoring displays (also configurable now :-) )
>  Make SMTP, anonymous login and theme configuratebil 

- dashboards/mgr-prometheus/mds-performance.json
We should use 'ceph_mds_sessions_sessions_open' instead of
'ceph_mds_sessions_session_count' to compute the number of (active)
clients. Otherwise, we include all the sessions, including the stale
ones.
Resolves: rhbz#1652896
This should fix the following downstream bz: https://bugzilla.redhat.com/show_bug.cgi?id=1652896
> dashboards: Show only open sessions

- ansible/roles/ceph-grafana/defaults/main.yml
- ansible/roles/ceph-grafana/tasks/setup_container.yml
- ansible/roles/ceph-prometheus/defaults/main.yml
- ansible/roles/ceph-prometheus/tasks/setup_container.yml
For the prometheus and grafana containers, in some specific
circumstances it's desirable to skip verification of the container
image. Allow passing that value in via group_vars.
Resolves: rhbz#1636136
> Allow skipping image verification

- ansible/group_vars/all.yml.sample
- ansible/roles/ceph-grafana/defaults/main.yml
- ansible/roles/ceph-grafana/tasks/configure_grafana.yml
This patch adds the grafana.overwrite_config option. You can change this
option if you want to keep your custom grafana configuration. The
scripts will still update the grafana config with the other configured
options but it won't overwrite your custom options.
This should fix the following bz: https://bugzilla.redhat.com/show_bug.cgi?id=1697336
> grafana: Add option to preserve grafana config

- ansible/roles/ceph-grafana/defaults/main.yml
The typo actually makes the ansible run fail if you don't have
smtp_enabled defined anywhere else.
> grafana: Fix typo in smtp configuration

- dashboards/mgr-prometheus/alert-status.json
Currently, we are sending an e-mail to the admin when the query returns
no data. This can get annoying as it does not mean that the alert has
actually been hit. We should fix this and alert only if the query says
we should.
Resolves: https://bugzilla.redhat.com/1663289
> prometheus: Silence no data alerts

- ansible/playbook.yml
This reverts commit 6f7559dfbb7b38463cf5c5d31f6ba1d8c7dcef0c.
We need to re-run the role on all mgr nodes to get firewalling rules properly updated.
> Revert "Only run ceph-mgr role on a single node"

- ansible/roles/ceph-mgr/tasks/main.yml
In d737083, we thought we were fixing something, but it turns out the
comparison suggested will throw an error if container_name contains a
dash (which it likely will). Revert the change and instruct
ansible-lint to not complain about that error on that line.
Resolves: rhbz#1731919
> Revert comparison "fix" from ansible-lint

- dashboards/mgr-prometheus/ceph-at-a-glance.json
- dashboards/mgr-prometheus/iops-by-server.json
- dashboards/mgr-prometheus/latency-by-server.json
The wal_device label was added to ceph_disk_occupation. We need to
ignore it in these queries to provide proper matching between values.
Otherwise, the query won't return any data. This is
backwards-compatible, if you ignore a non-existing label, nothing will
change.
> dashboards: Ignore wal_device label

- dashboards/mgr-prometheus/latency-by-server.json
The "All OSD Hosts - Highest Latency" chart's query was missing a
parenthesis, throwing numbers off by large amounts.
Resolves: rhbz#1650209
> DNM: dashboards: Fix broken disk latency chart
